using Test
using Nephrite

include("util.jl")

@testset "Nephrite" begin
    @testset "package loads" begin
        @test isdefined(Main, :Nephrite)
    end

    include("test_topology.jl")
    include("test_snapshots.jl")
    include("test_ingest.jl")
    include("test_datastore.jl")
    include("test_manifest.jl")
    include("test_hubmap.jl")
    include("test_supplycurves.jl")
    include("test_demand.jl")
    include("test_profile.jl")
    include("test_hydro.jl")
    include("test_fleet.jl")
    include("test_watervalues.jl")
    include("test_jadedata.jl")
    include("test_stationmap.jl")
    include("test_stationmap_real.jl")
    include("test_thermal.jl")
    include("test_hydronet.jl")
    include("test_wvanchor.jl")
    include("test_hydroenergy.jl")
    include("test_fixedstations.jl")
    include("test_dispatch.jl")
    include("test_master.jl")
    include("test_inflowscenarios.jl")
    include("test_inputs.jl")
    include("test_sddp.jl")
    include("test_jadecompare.jl")
    include("test_solver_smoke.jl")
    include("test_subproblem.jl")
    include("test_subproblem_spill.jl")
    include("test_runner.jl")
    include("test_outputs.jl")
    include("test_outputs_dist.jl")
    include("test_fcfshape.jl")
    include("test_fcfreconcile.jl")
    include("test_fcfexport.jl")
    include("test_fcfextract.jl")
    include("test_fcfsddp.jl")
    include("test_golden.jl")
    include("test_validate.jl")
    include("test_backfill_snapshots.jl")
    include("test_hmdstorage.jl")
    include("test_forwardprices.jl")
    include("test_backtestdata.jl")
    include("test_backtest.jl")
end
